_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  ROI_DENSEPOSE_HEAD:
    NAME: "DensePoseDeepLabHead"
    UV_CONFIDENCE:
      ENABLED: True
      TYPE: "iid_iso"
    POINT_REGRESSION_WEIGHTS: 0.0005
SOLVER:
  CLIP_GRADIENTS:
    ENABLED: True
  MAX_ITER: 130000
  STEPS: (100000, 120000)
