_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
  ROI_DENSEPOSE_HEAD:
    NAME: "DensePoseDeepLabHead"
SOLVER:
  # MAX_ITER: 130000
  MAX_ITER: 60000
  STEPS: (100000, 120000)
